name: Deploy
on:
  push:
    branches: [ 'master' ]
jobs:
  Deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          command_timeout: 60m
          script: |
            cd /home/themezer/Themezer
            pm2 stop /home/themezer/ecosystem.config.js --only Themezer
            git reset --hard
            git pull
            yarn
            rm -rfd /home/themezer/Themezer/.nuxt
            yarn run build
            pm2 reload /home/themezer/ecosystem.config.js --only Themezer
